[package]
name = "decktime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.6"
log = "0.4.22"
rusqlite = { version = "0.32.1", features = ["bundled"] }
